# Generated manually for Render-ready deployment
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(name='Category', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('name', models.CharField(max_length=100, unique=True)), ('slug', models.SlugField(blank=True, max_length=120, unique=True))], options={'verbose_name_plural': 'Catégories'}),
        migrations.CreateModel(name='ContactMessage', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('name', models.CharField(max_length=160)), ('email', models.EmailField(max_length=254)), ('subject', models.CharField(max_length=180)), ('message', models.TextField()), ('created_at', models.DateTimeField(auto_now_add=True)), ('is_read', models.BooleanField(default=False))], options={'ordering': ['-created_at']}),
        migrations.CreateModel(name='Service', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('title', models.CharField(max_length=160)), ('description', models.TextField()), ('price_note', models.CharField(blank=True, default='Sur devis', max_length=120)), ('is_active', models.BooleanField(default=True))]),
        migrations.CreateModel(name='SiteSetting', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('site_name', models.CharField(default='Estino Le Passionné', max_length=160)), ('tagline', models.CharField(default='Professeur • Chercheur • Écrivain', max_length=220)), ('phone', models.CharField(blank=True, default='(+228) 93 11 10 18 / 97 12 41 63', max_length=60)), ('whatsapp', models.CharField(blank=True, default='+22893111018', max_length=60)), ('email', models.EmailField(blank=True, default='leseditionstriomphetg@gmail.com', max_length=254)), ('address', models.CharField(default='Lomé, Togo', max_length=220)), ('hero_title', models.CharField(default='Livres, recherches et services pédagogiques', max_length=220)), ('hero_text', models.TextField(default='Découvrez les ouvrages, recueils, documents et prestations intellectuelles d’un professeur, chercheur et écrivain engagé pour la connaissance.')), ('biography', models.TextField(default='Estino Le Passionné, de son vrai nom AFE Komi, est professeur, écrivain et passionné de transmission du savoir. Son travail valorise la lecture, l’écriture, la pédagogie et les ressources éducatives accessibles.')), ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile/'))]),
        migrations.CreateModel(name='Book', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('title', models.CharField(max_length=180)), ('slug', models.SlugField(blank=True, max_length=220, unique=True)), ('author', models.CharField(default='Estino Le Passionné', max_length=120)), ('description', models.TextField()), ('price', models.PositiveIntegerField(help_text='Prix en FCFA')), ('format', models.CharField(choices=[('PDF', 'PDF'), ('DOCX', 'Word'), ('BOTH', 'PDF + Word')], default='PDF', max_length=20)), ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')), ('digital_file', models.FileField(blank=True, null=True, upload_to='documents/')), ('is_featured', models.BooleanField(default=False)), ('is_active', models.BooleanField(default=True)), ('created_at', models.DateTimeField(auto_now_add=True)), ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category'))], options={'ordering': ['-created_at']}),
        migrations.CreateModel(name='Order', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('full_name', models.CharField(max_length=160)), ('email', models.EmailField(max_length=254)), ('phone', models.CharField(max_length=60)), ('city', models.CharField(blank=True, max_length=120)), ('payment_method', models.CharField(choices=[('MOBILE_MONEY', 'Mobile Money'), ('MANUAL', 'Paiement manuel')], max_length=30)), ('status', models.CharField(choices=[('NEW', 'Nouvelle'), ('PAID', 'Payée'), ('DELIVERED', 'Livrée'), ('CANCELLED', 'Annulée')], default='NEW', max_length=20)), ('total', models.PositiveIntegerField(default=0)), ('download_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)), ('payment_reference', models.CharField(blank=True, max_length=120)), ('note', models.TextField(blank=True)), ('created_at', models.DateTimeField(auto_now_add=True))], options={'ordering': ['-created_at']}),
        migrations.CreateModel(name='OrderItem', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('quantity', models.PositiveIntegerField(default=1)), ('unit_price', models.PositiveIntegerField()), ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.book')), ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order'))]),
    ]
