services:
  - type: web
    name: professor
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn professor_market.wsgi:application"
    envVars:
      - key: DEBUG
        value: "0"
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "4"
      - key: PYTHON_VERSION
        value: "3.12.7"
databases:
  - name: professor-db
    databaseName: professor
    user: professor
